name: Format (PHP)
on:
    push:
        branches:
            - 'master'
    pull_request:
        paths:
            - '**.php'
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
